services:
  node1:
    container_name: node1
    command: ["sh", "-c", "app node --ip=$IP --miner=$$MINER --port=$PORT --data-dir=$DATA_DIR --bootstrap-account=$BOOTSTRAP_ACCOUNT --bootstrap-ip=$BOOTSTRAP_IP --bootstrap-port=$BOOTSTRAP_PORT"]
    build:
      context: .
    env_file:
      - .env
    environment:
      - MINER=0x9b0182B9a44181A22999A5c3e19B6dBBA9A4533A
    volumes:
      - ./var/tbb1:/home/node/.tbb
    restart: no
    ports: 
      - 8083:8080

  node2:
    container_name: node2
    command: ["sh", "-c", "app node --ip=$IP --miner=$$MINER --port=$PORT --data-dir=$DATA_DIR --bootstrap-account=$BOOTSTRAP_ACCOUNT --bootstrap-ip=$BOOTSTRAP_IP --bootstrap-port=$BOOTSTRAP_PORT"]
    build:
      context: .
    env_file:
      - .env
    environment:
      - MINER=0xD49E24193BDB3b5e7985846676C5C6cf0B124cAE
    volumes:
      - ./var/tbb2:/home/node/.tbb
    restart: no
    ports: 
      - 8084:8080

  node3:
    container_name: node3
    command: ["sh", "-c", "app node --ip=$IP --miner=$$MINER --port=$PORT --data-dir=$DATA_DIR --bootstrap-account=$BOOTSTRAP_ACCOUNT --bootstrap-ip=$BOOTSTRAP_IP --bootstrap-port=$BOOTSTRAP_PORT"]
    build:
      context: .
    env_file:
      - .env
    environment:
      - MINER=0x0E718900168F83f9C9177B43aA1fDdCd670e920E
    volumes:
      - ./var/tbb3:/home/node/.tbb
    restart: no
    ports: 
      - 8085:8080

